chore: typescript
ietf-tools/rpc pull request #160
Opened 2024-08-09 07:35 UTC by holloway

WIP

no need to review, just using github as offsite storage

2024-08-12 07:39 UTC, NGPixel requested changes

2024-08-12 07:39 UTC, NGPixel commented on client/app.vue
> +import { overlayModalKey, overlayModalMethodsKey } from './providers/providerKeys';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/components/AssignmentTrayItem.vue
> +import { deleteAssignmentKey } from '~/providers/providerKeys';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/components/AssignmentTrayItem.vue
> +if(!_deleteAssignment) throw Error("Sdfsdf")
Avoid single line if, use `{ }`. It's more verbose but it's clearer.

2024-08-12 07:39 UTC, NGPixel commented on client/components/AssignmentTrayItem.vue
> +const deleteAssignment= _deleteAssignment
Missing space before `=`

2024-08-12 07:39 UTC, NGPixel commented on client/components/Button.vue
> +  { btnType: 'default' },
No dangling comma

2024-08-12 07:39 UTC, NGPixel commented on client/components/DocumentCard.vue
> +import type { ADocument } from './DocumentCardsTypes';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/components/DocumentCard.vue
> +if(!_assignEditor) throw Error("Required assignEditor provider")
No single-line if

2024-08-12 07:39 UTC, NGPixel commented on client/components/DocumentCards.vue
> +import type { ADocument } from './DocumentCardsTypes';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/components/HeaderNav.vue
> +if (!_allUsers || !Array.isArray(_allUsers)) throw Error("Required allUsers data")
Avoid single-line if

2024-08-12 07:39 UTC, NGPixel commented on client/components/RpcLabelEditDialog.vue
> +if(!_overlayModalMethods) throw Error("Expected provider of overlayModalMethods")
Avoid single-line if

2024-08-12 07:39 UTC, NGPixel commented on client/components/RpcLabelPicker.vue
> +import type { Label } from '~/rpctracker_client';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/components/TestOverlay.vue
> +if(!overlayModalMethods) throw Error('overlayModalMethods used outside provider');
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/components/UserCreateDialog.vue
> +if(!overlayModalMethods) throw Error('overlayModalMethods used outside provider');
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/pages/auth48/[section].vue
> +import type { Column } from '~/components/DocumentTableTypes';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/pages/docs/[id].vue
> +      draftName: draft.value?.name ?? "",
Replace with single quotes

2024-08-12 07:39 UTC, NGPixel commented on client/pages/docs/assignments.vue
> +import type { Assignment } from '~/rpctracker_client';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/pages/docs/assignments.vue
> +    headers: { 'X-CSRFToken': csrf.value?.toString() ?? "" }
Replace with single quotes

2024-08-12 07:39 UTC, NGPixel commented on client/pages/docs/assignments.vue
> +    headers: { 'X-CSRFToken': csrf?.value ?? "" }
Replace with single quotes

2024-08-12 07:39 UTC, NGPixel commented on client/pages/index.vue
> +import { overlayModalKey } from '~/providers/providerKeys';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/pages/index.vue
> +if(!_overlayModal) throw Error("Require provider overlayModalKey")
Avoid single-line if

2024-08-12 07:39 UTC, NGPixel commented on client/pages/queue/[section].vue
> +import type { Column } from '~/components/DocumentTableTypes';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/pages/stats.vue
> +    default: () => ({ labelStats: [] }) as LabelStats,
No dangling comma

2024-08-12 07:39 UTC, NGPixel commented on client/pages/team/index.vue
> +import { overlayModalKey } from '~/providers/providerKeys';
No semicolons!

2024-08-12 07:39 UTC, NGPixel commented on client/pages/team/index.vue
> +if(!_overlayModal) throw Error("_overlayModal must be used in provider")
Avoid single-line if

2024-08-12 07:39 UTC, NGPixel commented on client/providers/providerKeys.ts
> +    cancel: () => void,
No dangling comma

2024-08-12 08:34 UTC, NGPixel commented on client/.eslintrc.js
> +import tseslint from 'typescript-eslint';
No semicolons!

2024-08-12 23:09 UTC, NGPixel requested changes
More linting police

2024-08-12 23:09 UTC, NGPixel commented on client/.eslintrc.js
> +    'plugin:@typescript-eslint/stylistic',
No dangling comma

2024-08-12 23:09 UTC, NGPixel commented on client/components/RpcLabel.vue
> +import type { Label } from '~/rpctracker_client';
No semicolons!

2024-08-20 10:06 UTC, holloway commented on client/.eslintrc.js
> +    parser: '@typescript-eslint/parser',
This seems to fix the broken linting fyi @NGPixel

2024-08-21 02:38 UTC, holloway commented
@NGPixel ready for a (hopefully final!) review

2024-08-21 13:16 UTC, rjsparks commented
All - please collapse resolved comments

2024-08-23 00:04 UTC, NGPixel approved these changes

2024-08-23 03:16 UTC, holloway commented
@jennifer-richards any chance this can be merged so that I can continue on Monday? Thanks!

2024-08-23 12:00 UTC, merged