feat: add pylint
ietf-tools/rpc pull request #188
Opened 2024-09-05 22:39 UTC by rjsparks

This builds on #187, and should be evaluated after that is merged.

It brings in a copy of the datatracker's .pylintrc, which we should review carefully.

2024-09-05 22:41 UTC, rjsparks commented on .pylintrc
> +ignore=CVS,migrations
CVS is vestigial
I'm surprised we're ignoring migrations.

2024-09-05 22:41 UTC, rjsparks commented on .pylintrc
> +# Add files or directories matching the regex patterns to the blacklist. The
blacklist

2024-09-05 22:43 UTC, rjsparks commented on .pylintrc
> +extension-pkg-whitelist=
whitelist

We may not control this name, but I wonder if it's still a valid configuration name?

2024-09-05 22:46 UTC, rjsparks commented on .pylintrc
> +optimize-ast=no
probably long gone - we are at pylint 3

2024-09-05 22:52 UTC, rjsparks commented on .pylintrc
> +overgeneral-exceptions=builtins.Exception
anachronism?

2024-09-05 23:14 UTC, rjsparks commented on .pylintrc
> +[MASTER]
MASTER (new pylint generates MAIN)

2024-09-05 23:17 UTC, rjsparks commented on .pylintrc
> +ignore=CVS,migrations
new pylint --generate-rcfile generates this same set

2024-09-05 23:19 UTC, rjsparks commented on .pylintrc
> +extension-pkg-whitelist=
from a newly generated rc:
```
# A comma-separated list of package or module names from where C extensions may
# be loaded. Extensions are loading into the active Python interpreter and may
# run arbitrary code. (This is an alternative name to extension-pkg-allow-list
# for backward compatibility.)
extension-pkg-whitelist=
```

2024-09-05 23:19 UTC, rjsparks commented on .pylintrc
> +optimize-ast=no
confirmed - no longer relevant

2024-09-09 15:14 UTC, jennifer-richards requested changes
I think we should take the lessons from here and go with #189 instead

2024-09-09 16:19 UTC, closed without merging